-- @description Every system catalog, view and statistics view PostgreSQL documents, in one list; the name browses its rows
-- @face result
select v.relation, v.what, v.family
from (values
    ('pg_aggregate', 'aggregate functions', 'catalog'),
    ('pg_am', 'relation access methods', 'catalog'),
    ('pg_amop', 'access method operators', 'catalog'),
    ('pg_amproc', 'access method support functions', 'catalog'),
    ('pg_attrdef', 'column default values', 'catalog'),
    ('pg_attribute', 'table columns ("attributes")', 'catalog'),
    ('pg_authid', 'authorization identifiers (roles)', 'catalog'),
    ('pg_auth_members', 'authorization identifier membership relationships', 'catalog'),
    ('pg_cast', 'casts (data type conversions)', 'catalog'),
    ('pg_class', 'tables, indexes, sequences, views ("relations")', 'catalog'),
    ('pg_collation', 'collations (locale information)', 'catalog'),
    ('pg_constraint', 'check, unique, primary key and foreign key constraints', 'catalog'),
    ('pg_conversion', 'encoding conversion information', 'catalog'),
    ('pg_database', 'databases within this database cluster', 'catalog'),
    ('pg_db_role_setting', 'per-role and per-database settings', 'catalog'),
    ('pg_default_acl', 'default privileges for object types', 'catalog'),
    ('pg_depend', 'dependencies between database objects', 'catalog'),
    ('pg_description', 'descriptions or comments on database objects', 'catalog'),
    ('pg_enum', 'enum label and value definitions', 'catalog'),
    ('pg_event_trigger', 'event triggers', 'catalog'),
    ('pg_extension', 'installed extensions', 'catalog'),
    ('pg_foreign_data_wrapper', 'foreign-data wrapper definitions', 'catalog'),
    ('pg_foreign_server', 'foreign server definitions', 'catalog'),
    ('pg_foreign_table', 'additional foreign table information', 'catalog'),
    ('pg_index', 'additional index information', 'catalog'),
    ('pg_inherits', 'table inheritance hierarchy', 'catalog'),
    ('pg_init_privs', 'object initial privileges', 'catalog'),
    ('pg_language', 'languages for writing functions', 'catalog'),
    ('pg_largeobject', 'data pages for large objects', 'catalog'),
    ('pg_largeobject_metadata', 'metadata for large objects', 'catalog'),
    ('pg_namespace', 'schemas', 'catalog'),
    ('pg_opclass', 'access method operator classes', 'catalog'),
    ('pg_operator', 'operators', 'catalog'),
    ('pg_opfamily', 'access method operator families', 'catalog'),
    ('pg_parameter_acl', 'configuration parameters for which privileges have been granted', 'catalog'),
    ('pg_partitioned_table', 'information about partition key of tables', 'catalog'),
    ('pg_policy', 'row-security policies', 'catalog'),
    ('pg_proc', 'functions and procedures', 'catalog'),
    ('pg_propgraph_element', 'property graph elements (vertices and edges)', 'catalog'),
    ('pg_propgraph_element_label', 'property graph links between elements and labels', 'catalog'),
    ('pg_propgraph_label', 'property graph labels', 'catalog'),
    ('pg_propgraph_label_property', 'property graph label-specific property definitions', 'catalog'),
    ('pg_propgraph_property', 'property graph properties', 'catalog'),
    ('pg_publication', 'publications for logical replication', 'catalog'),
    ('pg_publication_namespace', 'schema to publication mapping', 'catalog'),
    ('pg_publication_rel', 'relation to publication mapping', 'catalog'),
    ('pg_range', 'information about range types', 'catalog'),
    ('pg_replication_origin', 'registered replication origins', 'catalog'),
    ('pg_rewrite', 'query rewrite rules', 'catalog'),
    ('pg_seclabel', 'security labels on database objects', 'catalog'),
    ('pg_sequence', 'information about sequences', 'catalog'),
    ('pg_shdepend', 'dependencies on shared objects', 'catalog'),
    ('pg_shdescription', 'comments on shared objects', 'catalog'),
    ('pg_shseclabel', 'security labels on shared database objects', 'catalog'),
    ('pg_statistic', 'planner statistics', 'catalog'),
    ('pg_statistic_ext', 'extended planner statistics (definition)', 'catalog'),
    ('pg_statistic_ext_data', 'extended planner statistics (built statistics)', 'catalog'),
    ('pg_subscription', 'logical replication subscriptions', 'catalog'),
    ('pg_subscription_rel', 'relation state for subscriptions', 'catalog'),
    ('pg_tablespace', 'tablespaces within this database cluster', 'catalog'),
    ('pg_transform', 'transforms (data type to procedural language conversions)', 'catalog'),
    ('pg_trigger', 'triggers', 'catalog'),
    ('pg_ts_config', 'text search configurations', 'catalog'),
    ('pg_ts_config_map', 'text search configurations'' token mappings', 'catalog'),
    ('pg_ts_dict', 'text search dictionaries', 'catalog'),
    ('pg_ts_parser', 'text search parsers', 'catalog'),
    ('pg_ts_template', 'text search templates', 'catalog'),
    ('pg_type', 'data types', 'catalog'),
    ('pg_user_mapping', 'mappings of users to foreign servers', 'catalog'),
    ('pg_aios', 'in-use asynchronous IO handles', 'view'),
    ('pg_available_extensions', 'available extensions', 'view'),
    ('pg_available_extension_versions', 'available versions of extensions', 'view'),
    ('pg_backend_memory_contexts', 'backend memory contexts', 'view'),
    ('pg_config', 'compile-time configuration parameters', 'view'),
    ('pg_cursors', 'open cursors', 'view'),
    ('pg_dsm_registry_allocations', 'shared memory allocations tracked in the DSM registry', 'view'),
    ('pg_file_settings', 'summary of configuration file contents', 'view'),
    ('pg_group', 'groups of database users', 'view'),
    ('pg_hba_file_rules', 'summary of client authentication configuration file contents', 'view'),
    ('pg_ident_file_mappings', 'summary of client user name mapping configuration file contents', 'view'),
    ('pg_indexes', 'indexes', 'view'),
    ('pg_locks', 'locks currently held or awaited', 'view'),
    ('pg_matviews', 'materialized views', 'view'),
    ('pg_policies', 'policies', 'view'),
    ('pg_prepared_statements', 'prepared statements', 'view'),
    ('pg_prepared_xacts', 'prepared transactions', 'view'),
    ('pg_publication_sequences', 'publications and information of their associated sequences', 'view'),
    ('pg_publication_tables', 'publications and information of their associated tables', 'view'),
    ('pg_replication_origin_status', 'information about replication origins, including replication progress', 'view'),
    ('pg_replication_slots', 'replication slot information', 'view'),
    ('pg_roles', 'database roles', 'view'),
    ('pg_rules', 'rules', 'view'),
    ('pg_seclabels', 'security labels', 'view'),
    ('pg_sequences', 'sequences', 'view'),
    ('pg_settings', 'parameter settings', 'view'),
    ('pg_shadow', 'database users', 'view'),
    ('pg_shmem_allocations', 'shared memory allocations', 'view'),
    ('pg_shmem_allocations_numa', 'NUMA node mappings for shared memory allocations', 'view'),
    ('pg_stats', 'planner statistics', 'view'),
    ('pg_stats_ext', 'extended planner statistics', 'view'),
    ('pg_stats_ext_exprs', 'extended planner statistics for expressions', 'view'),
    ('pg_tables', 'tables', 'view'),
    ('pg_timezone_abbrevs', 'time zone abbreviations', 'view'),
    ('pg_timezone_names', 'time zone names', 'view'),
    ('pg_user', 'database users', 'view'),
    ('pg_user_mappings', 'user mappings', 'view'),
    ('pg_views', 'views', 'view'),
    ('pg_wait_events', 'wait events', 'view'),
    ('pg_stat_activity', 'one row per server process, its state and current query', 'statistics'),
    ('pg_stat_replication', 'one row per WAL sender, replication to its connected standby', 'statistics'),
    ('pg_stat_wal_receiver', 'the WAL receiver, statistics from its connected server', 'statistics'),
    ('pg_stat_recovery', 'the recovery state, at most one row', 'statistics'),
    ('pg_stat_recovery_prefetch', 'blocks prefetched during recovery', 'statistics'),
    ('pg_stat_subscription', 'subscription workers, at least one row per subscription', 'statistics'),
    ('pg_stat_ssl', 'SSL on each connection, one row per connection', 'statistics'),
    ('pg_stat_gssapi', 'GSSAPI authentication and encryption on each connection', 'statistics'),
    ('pg_stat_archiver', 'the WAL archiver process''s activity, one row', 'statistics'),
    ('pg_stat_bgwriter', 'the background writer process''s activity, one row', 'statistics'),
    ('pg_stat_checkpointer', 'the checkpointer process''s activity, one row', 'statistics'),
    ('pg_stat_database', 'database-wide statistics, one row per database', 'statistics'),
    ('pg_stat_database_conflicts', 'query cancels due to recovery conflicts on standbys, per database', 'statistics'),
    ('pg_stat_io', 'cluster-wide I/O, per backend type, context and target object', 'statistics'),
    ('pg_stat_lock', 'cluster-wide lock statistics, one row per lock type', 'statistics'),
    ('pg_stat_replication_slots', 'replication slot usage, one row per slot', 'statistics'),
    ('pg_stat_slru', 'SLRU cache operations, one row per SLRU', 'statistics'),
    ('pg_stat_subscription_stats', 'subscription errors and conflicts, one row per subscription', 'statistics'),
    ('pg_stat_wal', 'WAL activity, one row', 'statistics'),
    ('pg_stat_all_tables', 'access statistics for every table in the current database', 'statistics'),
    ('pg_stat_sys_tables', 'pg_stat_all_tables, system tables only', 'statistics'),
    ('pg_stat_user_tables', 'pg_stat_all_tables, user tables only', 'statistics'),
    ('pg_stat_xact_all_tables', 'table actions of the current transaction, not yet in pg_stat_all_tables', 'statistics'),
    ('pg_stat_xact_sys_tables', 'pg_stat_xact_all_tables, system tables only', 'statistics'),
    ('pg_stat_xact_user_tables', 'pg_stat_xact_all_tables, user tables only', 'statistics'),
    ('pg_stat_autovacuum_scores', 'current autovacuum scores for every table in the current database', 'statistics'),
    ('pg_stat_all_indexes', 'access statistics for every index in the current database', 'statistics'),
    ('pg_stat_sys_indexes', 'pg_stat_all_indexes, indexes on system tables only', 'statistics'),
    ('pg_stat_user_indexes', 'pg_stat_all_indexes, indexes on user tables only', 'statistics'),
    ('pg_stat_user_functions', 'executions of each tracked function', 'statistics'),
    ('pg_stat_xact_user_functions', 'tracked function calls of the current transaction', 'statistics'),
    ('pg_statio_all_tables', 'I/O statistics for every table in the current database', 'statistics'),
    ('pg_statio_sys_tables', 'pg_statio_all_tables, system tables only', 'statistics'),
    ('pg_statio_user_tables', 'pg_statio_all_tables, user tables only', 'statistics'),
    ('pg_statio_all_indexes', 'I/O statistics for every index in the current database', 'statistics'),
    ('pg_statio_sys_indexes', 'pg_statio_all_indexes, indexes on system tables only', 'statistics'),
    ('pg_statio_user_indexes', 'pg_statio_all_indexes, indexes on user tables only', 'statistics'),
    ('pg_statio_all_sequences', 'I/O statistics for every sequence in the current database', 'statistics'),
    ('pg_statio_sys_sequences', 'pg_statio_all_sequences, system sequences only (none exist, always empty)', 'statistics'),
    ('pg_statio_user_sequences', 'pg_statio_all_sequences, user sequences only', 'statistics'),
    ('pg_stat_progress_analyze', 'every backend running ANALYZE, its progress', 'progress'),
    ('pg_stat_progress_basebackup', 'every WAL sender streaming a base backup, its progress', 'progress'),
    ('pg_stat_progress_cluster', 'every backend running CLUSTER or VACUUM FULL, its progress', 'progress'),
    ('pg_stat_progress_copy', 'every backend running COPY, its progress', 'progress'),
    ('pg_stat_progress_create_index', 'every backend running CREATE INDEX or REINDEX, its progress', 'progress'),
    ('pg_stat_progress_data_checksums', 'the data checksum launcher (and workers) while checksums are enabled or disabled', 'progress'),
    ('pg_stat_progress_repack', 'every backend running REPACK, CLUSTER or VACUUM FULL, its progress', 'progress'),
    ('pg_stat_progress_vacuum', 'every backend running VACUUM, its progress', 'progress')
) as v(relation, what, family)
order by v.family, v.relation;

-- @open browse
-- @on relation
-- @inline relation identifier
select * from pg_catalog.$relation;
